name: "Podcast Generator--v1"
author: "Danidu Kavishan"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding: 
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiter's emial address
    required: ture
    default: ${{ github.actor }}@localhost
  name:
    description: The commiter's name
    required: ture
    default: ${{ github.actor }}
